### ISSUE TITLE
Periodic job to healthcheck URLs

### ISSUE THREAD

**Issue by 0xmichalis** [DefiLlama/defillama-server#1344]
It may be useful to have a job run on a Github action run periodically (daily or weekly) to healthcheck all links found across all projects so you can get alerted and weed out dead links as soon as they are broken.

Example workflow: https://github.com/kargakis/awesome-carbon/blob/main/.github/workflows/ci.yml

**Comment by 0xngmi** [comment]
good idea, i created a CI workflow for it: https://github.com/DefiLlama/defillama-server/blob/master/.github/workflows/check-urls.yml

btw as you can see we are quite bad at checking github issues (reason is that almost nobody contacts us this way), so in the future might be better to use discord or ping me directly if you opened an issue but haven't gotten any reply on it (it's just that we didn't see it!)
