### ISSUE TITLE
Update the docs about slugs

### ISSUE THREAD

**Issue by diegoramosxyz** [DefiLlama/defillama-server#15]
The defillama API already responds with the slug for each DeFi protocol, however [the documentation](https://docs.llama.fi/api#get-protocol) makes no mention of it. Where can I contribute to make that change?

I think the documentation should also include the Protocol interface. Anyone using TypeScript would greatly appreciate it.

https://github.com/DefiLlama/defillama-server/blob/74ea7d7ac9a492569c011871eeec6e7c839f1f2b/src/protocols/data.ts#L3-L20

**Comment by 0xngmi** [comment]
I'm setting up an integration of our docs with github so you'll be able to make edits directly there, hopefully that helps make the process much easier :smile:

**Comment by 0xngmi** [comment]
I've mirrored all our docs to [DefiLlama/docs](https://github.com/DefiLlama/docs), feel free to contribute any changes you want there (and drop your address on the PR if you want to receive a llamapunk).

**Comment by diegoramosxyz** [comment]
Unfortunately, the PR I made on the [docs](https://github.com/DefiLlama/docs) has some issues. Basically [this entire page](https://docs.llama.fi/api) is messed up. Let me know if I can fix without the integration or perhaps this is something that you could handle since the data is already there.

**Comment by 0xngmi** [comment]
I just saw, I'll try to fix directly using gitbook's interface

**Comment by 0xngmi** [comment]
Just updated it, now it should match your changes
