### ISSUE TITLE
Fix multiverseC2C website

### ISSUE THREAD

**Issue by dc199411** [DefiLlama/defillama-server#3310]
the website for the recently added multiverseC2C was typed wrong when submitted I have tried creating a PR but somehow it has a conflict with the main branch could you please update it to [https://multiverse.fntokens.xyz](https://multiverse.fntokens.xyz)

**Comment by Define101** [comment]
Seems good now right?

**Comment by dc199411** [comment]
no it's loading as this [https://mulitverse.fntokens.xyz/cgi-bin/index.cgi](https://mulitverse.fntokens.xyz/cgi-bin/index.cgi)  when it should be this https://multiverse.fntokens.xyz

**Comment by Define101** [comment]
https://github.com/DefiLlama/defillama-server/commit/4beddb1aa6aacc00532d135503594d7a1de75b44
