### ISSUE TITLE
Adding Supra's Oracle to Mirakle Defi

### ISSUE THREAD

**Issue by ksdumont** [DefiLlama/defillama-server#4815]
Hi,
We would like to add the use of Supra's Oracle to Mirakle Defi. Their dynamic pricing is supported by SupraOracles.

Materials
-> https://mirakle.gitbook.io/home/

Rationale
Mirakle Defi uses Supra's oracle for dynamic pricing of the following assets: btc/usdt, eth/usdt, and fuse/usdt

Thank you in advance. 

Best,
Keith

**Comment by Define101** [comment]
Hello ksdumont
I dont think we are tracking that project
Could you ask them to make a PR in our adapter repo?
https://docs.llama.fi/list-your-project/submit-a-project

**Comment by ksdumont** [comment]
Yes, I will let them know now and get back to you. Thanks for the prompt response.

**Comment by Define101** [comment]
Hello @ksdumont happy to inform you that we have listed Mirakle Defi, we have also added Supra Oracles as their oracle
Thanks for letting us know 
https://defillama.com/protocol/mirakle-defi

**Comment by Define101** [comment]
Hello @ksdumont its there, please refresh your page 
![image](https://github.com/DefiLlama/defillama-server/assets/93603962/613a322e-81e1-4453-866e-0e10c892da81)

**Comment by Define101** [comment]
Can i close this issue?

**Comment by Define101** [comment]
Ok we can keep this issue open.
So if you want to add more pls let us know here

**Comment by ksdumont** [comment]
Hi,
We would like to add the use of Supra's Oracle to Bucket Protocol. Their pricing of SUI_USDT, USDC_USD, and ETH_USD is supported by SupraOracles. They are on the Sui Blockchain.

Materials
-> https://github.com/Bucket-Protocol/oracle/tree/mainnet

Rationale
Bucket Protocol uses Supra's oracle for pricing of the following assets: SUI_USDT, USDC_USD, and ETH_USD

Thank you in advance. Let me know if you need any more info. 

Best,
Keith

**Comment by realdealshaman** [comment]
@ksdumont, thank you for bringing this to our attention. I've successfully added Supra to Bucket Protocol. For future reference, the ideal way to request the inclusion of Supra oracle in a project is by submitting a pull request to the appropriate protocol listing file, which could be either data.ts, data2.ts, or data3.ts.

**Comment by ksdumont** [comment]
Thank you, I don't see it added [here](https://defillama.com/oracles/Supra%20Oracles) yet. How long does it usually take to show? 
Also, we will be adding many more projects in the near future, can you link to exactly where I should be making the pull requests?

**Comment by ksdumont** [comment]
Following up on this.

**Comment by Define101** [comment]
Yes we have made that
This page should not exist https://defillama.com/oracles/Supra%20Oracles
