### ISSUE TITLE
Adding Wrapped Staked Ether (wstETH) on Starknet

### ISSUE THREAD

**Issue by 9oelM** [DefiLlama/defillama-server#4961]
Currently, only 5 starknet tokens are supported:

https://github.com/DefiLlama/defillama-server/blob/37559eb6a39969bb33b49ba93d95bd876d8e7f10/coins/src/adapters/tokenMapping_added.json#L4723-L4754

You can verify it by sending a request to:

https://coins.llama.fi/prices/current/starknet:0x00da114221cb83fa859dbdb4c44beeaa0bb37c7537ad5ae66fe5e0efd20e6eb3,starknet:0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8,starknet:0x068f5c6a61780768455de69077e07e89787839bf8166decfbf92b645209c0fb8,starknet:0x03fe2b97c1fd336e750087d68b9b867997fd64a2661ff3ca5a7c771641e8e7ac,starknet:0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7

However I want support for `starknet:0x042b8f0484674ca266ac5d08e4ac6a3fe65bd3129795def2dca5c34ecc5f96d2` to be added, which is [wstETH on Starknet](https://starkscan.co/token/0x042b8f0484674ca266ac5d08e4ac6a3fe65bd3129795def2dca5c34ecc5f96d2).

But what I cannot understand is that I have tried to read https://docs.llama.fi/coin-prices-api and follow the direction there, but how come some starknet tokens are already supported despite the absence of `coins/src/adapters/bridges/starknet.ts`? From what I understood, I should create `coins/src/adapters/bridges/starknet.ts` and define `export default async function bridge` that would get the list of tokens from starknet.

Anyway, if you find it easier to just add a support for it directly, that would be great too, otherwise please let me know if what I think I should do is right.

**Comment by Define101** [comment]
Thanks for inform us
We have added the price for wsETH on starknet
Should be live within 2 hours

**Comment by 9oelM** [comment]
Thanks a lot 👍

**Comment by 9oelM** [comment]
https://coins.llama.fi/prices/current/starknet:0x042b8f0484674ca266ac5d08e4ac6a3fe65bd3129795def2dca5c34ecc5f96d2

working perfectly. closing.

**Comment by Define101** [comment]
No problem
