### ISSUE TITLE
missing GAI token

### ISSUE THREAD

**Issue by web3jackkkk** [DefiLlama/defillama-server#5065]
https://coins.llama.fi/prices/current/manta:0xcd91716ef98798a85e79048b78287b13ae6b99b2

<img width="370" alt="image" src="https://github.com/DefiLlama/defillama-server/assets/150323222/201cb15a-24e5-45d3-8e4b-f18ef77a7480">

please add GAI (manta) token

GAI TOKEN: 
https://www.geckoterminal.com/manta-pacific/pools/0x357198ade95152e4fec8ad4d63981f45c4ab16c3?utm_source=coingecko&utm_medium=referral&utm_campaign=searchresults

**Comment by g1nt0ki** [comment]
@web3jackkkk I dont see enough liquidity (10k DAI atm, we have a baseline of at 50k) think thats why the price is not getting picked up. Other option is getting the token listed on coingecko (not geckoterminal), we pull prices from it

**Comment by web3jackkkk** [comment]
Thanks for the heads up. we are working on it.

**Comment by web3jackkkk** [comment]
Hi @g1nt0ki, We've increased the liquidity to 50K+. please take a look at it from 
https://dexscreener.com/manta/0x357198ade95152e4fec8ad4d63981f45c4ab16c3
<img width="372" alt="image" src="https://github.com/DefiLlama/defillama-server/assets/150323222/4787cd24-901b-4f4e-a3d8-abf93e84a7d8">
