### ISSUE TITLE
Wrong GAI price

### ISSUE THREAD

**Issue by web3jackkkk** [DefiLlama/defillama-server#5102]
Currently: https://coins.llama.fi/prices/current/manta:0xcd91716ef98798a85e79048b78287b13ae6b99b2
<img width="750" alt="image" src="https://github.com/DefiLlama/defillama-server/assets/150323222/90af05bb-e8d8-4e05-9bb2-468c4e98d8f5">

Expect: https://www.coingecko.com/en/coins/goku-money-gai
<img width="754" alt="image" src="https://github.com/DefiLlama/defillama-server/assets/150323222/d35c9158-0829-493a-9af6-24ef1524eb76">

**Comment by waynebruce0x** [comment]
This should be fixed now, closing the isse. Please contact us through Discord if you have any further questions etc
