### ISSUE TITLE
childProtocols is not being returned from "summary/dexs" endpoint

### ISSUE THREAD

**Issue by ocozalp** [DefiLlama/defillama-server#6252]
`childProtocols` is not being returned from the summary endpoint and in the example case below, only 1 version of the protocol is being returned. 

To reproduce: https://api.llama.fi/summary/dexs/uniswap?excludeTotalDataChart=true&excludeTotalDataChartBreakdown=true&dataType=dailyVolume

**Comment by Define101** [comment]
Thanks for the report
We are looking into this @ocozalp

**Comment by Define101** [comment]
@ocozalp On the dexs endpoint, not possible to grab the parentProtocol
On that case, its grabing the v1 
If you replace it with uniswap-v2 or v3 you will get those versions TVL

**Comment by ocozalp** [comment]
@Define101 previously we pass the parent protocol as input (`uniswap`), get child protocols and get protocol volumes for each child protocol. Is it changed now, should I just pass `uniswap-v3` instead?

**Comment by Define101** [comment]
@ocozalp hello could you please check again? Should be good now
https://[api.llama.fi/summary/dexs/uniswap?excludeTotalDataChart=true&excludeTotalDataChartBreakdown=true&dataType=dailyVolume](https://api.llama.fi/summary/dexs/uniswap?excludeTotalDataChart=true&excludeTotalDataChartBreakdown=true&dataType=dailyVolume)
![image](https://github.com/DefiLlama/defillama-server/assets/93603962/5c9111ad-5269-4a6e-8063-ba016079f2b9)

**Comment by ocozalp** [comment]
Thanks, it works now.
