### ISSUE TITLE
Add ZEND to Starknet

### ISSUE THREAD

**Issue by 9oelM** [DefiLlama/defillama-server#6415]
Currently, ZEND (zkLend token) isn't supported. This can be confirmed by sending a request to

https://coins.llama.fi/prices/current/starknet:0x00585c32b625999e6e5e78645ff8df7a9001cf5cf3eb6b80ccdd16cb64bd3a34

ZEND has been listed on Bybit and Kucoin:
- https://www.kucoin.com/trade/ZEND-USDT
- https://www.bybit.com/en/trade/spot/ZEND/USDT

Would be great if the server can support it, so I can make changes to DefiLlama-Adapters for ZEND staking

**Comment by Define101** [comment]
https://github.com/DefiLlama/defillama-server/pull/6420
Should be good within 2 hours

**Comment by g1nt0ki** [comment]
@9oelM isnt this the zend address? https://coins.llama.fi/prices/current/starknet:0x05ffbcfeb50d200a0677c48a129a11245a3fc519d1d98d76882d1c9a1b19c6ed

**Comment by 9oelM** [comment]
> @9oelM isnt this the zend address? https://coins.llama.fi/prices/current/starknet:0x05ffbcfeb50d200a0677c48a129a11245a3fc519d1d98d76882d1c9a1b19c6ed

Hey now i can see the response. Thank you very much :)

**Comment by 9oelM** [comment]
@g1nt0ki @Define101 wait, `0x05ffbcfeb50d200a0677c48a129a11245a3fc519d1d98d76882d1c9a1b19c6ed` is not the ZEND address. It is the address of the class hash of the contract address on Starknet. [`0x00585c32b625999e6e5e78645ff8df7a9001cf5cf3eb6b80ccdd16cb64bd3a34`](https://starkscan.co/contract/0x00585c32b625999e6e5e78645ff8df7a9001cf5cf3eb6b80ccdd16cb64bd3a34) is the correct token address. Can I request a change? Thank you.

**Comment by 9oelM** [comment]
Resolvef by #6470
