### ISSUE TITLE
Coins API does not return the price of Renzo's ezETH properly.

### ISSUE THREAD

**Issue by deadshotryker** [DefiLlama/defillama-server#6442]
Hello,

The price for Renzo ezETH on Linea does not seem to load up properly even though the address and asset is tracked on CoinGecko.

The endpoint https://coins.llama.fi/prices/current/linea:0x2416092f143378750bb29b79ed961ab195cceea5 

Returns a blank response

```
{
"coins": {}
}
```
On CoinGecko you can verify that the address for ezETH is properly set 0x2416092f143378750bb29b79ed961ab195cceea5.

CoinGecko: https://www.coingecko.com/en/coins/renzo-restaked-eth

Unsure if this has anything to do with CG returning `null` for the decimals for the above asset. 

https://api.coingecko.com/api/v3/coins/linea/contract/0x2416092f143378750bb29b79ed961ab195cceea5

<img width="865" alt="image" src="https://github.com/DefiLlama/defillama-server/assets/151393124/ee7f6060-9652-48a8-ba0f-853fedc5db3f">

**Comment by Define101** [comment]
Please check again
Is good now

**Comment by deadshotryker** [comment]
Appreciated ser 🖖
