### ISSUE TITLE
"Wingriders DEX" audit is not an audit but a blog article

### ISSUE THREAD

**Issue by nielstron** [DefiLlama/defillama-server#700]
The real audit is listed here: https://www.certik.com/projects/wingriders
The corresponding github repository by CertiK leads to 404 (https://github.com/WingRiders/core-contracts/tree/audit). No complete audit is provided anywhere.

https://github.com/DefiLlama/fees-server/blob/5941938a1627d3bed00d590937f329e5a0b6c3e6/src/utils/protocols/data2.ts#L4229

**Comment by Define101** [comment]
Hi nielstron
Thanks for letting us know, changes have been made, and should reflect on the website within 1 hour
