### ISSUE TITLE
"MinSwap DEX" audit leads to 404

### ISSUE THREAD

**Issue by nielstron** [DefiLlama/defillama-server#701]
The link to the audit of the MinSwap protocol on Cardano does not lead to a valid audit file (it goes to 404)

https://github.com/DefiLlama/fees-server/blob/5941938a1627d3bed00d590937f329e5a0b6c3e6/src/utils/protocols/data2.ts#L1895

**Comment by Define101** [comment]
Seems that they deleted from their repo
Do you have the new link? Cant find it in their docs/website

**Comment by nielstron** [comment]
AFAIK there is either no new audit or it has not yet been published.

**Comment by nielstron** [comment]
The audit linked previously was for a vulnerable version of the contract. Hence the contract has been deleted since and the audit as well.
See this blog article: https://minswap-labs.medium.com/vulnerability-patch-technical-details-and-steps-forward-97f6ee35aa91

**Comment by Define101** [comment]
Thanks for the info
I just removed the audit link, once they have a new one we will add it

**Comment by 0xngmi** [comment]
closing this since it's already been fixed
