### ISSUE TITLE
how do i add a Protocol

### ISSUE THREAD

**Issue by MengZhaoFly** [DefiLlama/defillama-server#7159]
hi, I have read this guide https://docs.llama.fi/list-your-project/how-to-update-a-project
I know that I need to complete an adapter, but the adapter only defines how to calculate TVL, and has nothing to do with the protocol (name, official website, logo...). How can I add my protocol?

**Comment by MengZhaoFly** [comment]
and I noticed PRs like this（https://github.com/DefiLlama/defillama-server/pull/7154/files）, but these PRs seem to be initiated by official developers

**Comment by Define101** [comment]
@MengZhaoFly hello. You just need to make a Pull Request on the adapter side. We wil make a listing for it
